language: node_js
sudo: false
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '13'
after_success:
  - NPM_TOKEN=$NPM_TOKEN GH_TOKEN=$GH_TOKEN yarn semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/